version: '3.1'
services:
  stats-server:
    build: stats
    restart: always
    image: ewm-stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore-stats

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ewm
    restart: always
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore-ewm

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
