CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(255) NOT NULL,
  email         VARCHAR(512) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(255) NOT NULL,
  CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORIES_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
  id            	    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation 		    VARCHAR(2000) NOT NULL,
  category_id		    BIGINT,
  confirmed_requests	BIGINT,
  created_on            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  description		    VARCHAR(2000) NOT NULL,
  event_date		    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  initiator_id		    BIGINT,
  lat			        DECIMAL,
  lon                   DECIMAL,
  paid			        BOOLEAN NOT NULL,
  participant_limit 	BIGINT,
  published_on		    TIMESTAMP WITHOUT TIME ZONE,
  request_moderation	BOOLEAN,
  state                 VARCHAR(32),
  title			        VARCHAR(2000),
  views                 BIGINT,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT FK_EVENTS_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id),
  CONSTRAINT FK_EVENTS_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS event_request (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  event_id      BIGINT,
  requester_id  BIGINT,
  status 	    VARCHAR(32) NOT NULL,
  CONSTRAINT pk_events_request PRIMARY KEY (id),
  CONSTRAINT FK_EVENT_REQUEST_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT FK_EVENT_REQUEST_EVENTS FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned	BOOLEAN,
  title		VARCHAR(2000),
  CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilation (
  event_id      	BIGINT,
  compilation_id	BIGINT,
  CONSTRAINT pk_event_compilation PRIMARY KEY (event_id, compilation_id),
  CONSTRAINT FK_EVENT_COMPILATION_EVENTS FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT FK_EVENT_COMPILATION_COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

